# Generated by Django 3.0.2 on 2020-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cusm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('custnum', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('occupency', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('idtype', models.CharField(max_length=2)),
                ('idnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='masteraccountnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='mastercustomernumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customernumber', models.CharField(max_length=16)),
            ],
        ),
    ]
