# Generated by Django 3.0.5 on 2020-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cusm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('custnum', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('occupency', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('idtype', models.CharField(max_length=2)),
                ('idnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='glif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=16)),
                ('drcr', models.CharField(max_length=2)),
                ('balbefore', models.CharField(max_length=17)),
                ('balafter', models.CharField(max_length=17)),
                ('tranamt', models.CharField(max_length=17)),
                ('trandate', models.CharField(max_length=15)),
                ('sysnarr', models.CharField(max_length=50)),
                ('usernarr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='invm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=16)),
                ('custnum', models.CharField(max_length=16)),
                ('acctype', models.CharField(max_length=2)),
                ('opendate', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=2)),
                ('curency', models.CharField(max_length=3)),
                ('balance', models.CharField(max_length=17)),
                ('accname', models.CharField(max_length=50)),
                ('intrest', models.CharField(max_length=3)),
                ('intfreq', models.CharField(max_length=5)),
                ('matdate', models.CharField(max_length=15)),
                ('narration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='masteraccountnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='mastercustomernumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customernumber', models.CharField(max_length=16)),
            ],
        ),
    ]
