# Generated by Django 3.0.2 on 2020-04-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_invm'),
    ]

    operations = [
        migrations.CreateModel(
            name='glif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=16)),
                ('drcr', models.CharField(max_length=2)),
                ('balbefore', models.CharField(max_length=17)),
                ('balafter', models.CharField(max_length=17)),
                ('tranamt', models.CharField(max_length=17)),
                ('trandate', models.CharField(max_length=15)),
                ('sysnarr', models.CharField(max_length=50)),
                ('usernarr', models.CharField(max_length=50)),
            ],
        ),
    ]
